// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using DataCommunicator.Models;

#nullable disable

namespace DataCommunicator.Context
{
    public partial class CentraldbContext : DbContext
    {
        public CentraldbContext()
        {
        }

        public CentraldbContext(DbContextOptions<CentraldbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<SystemConfig> SystemConfig { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=CentralDB;Integrated Security=true");

            modelBuilder.Entity<Modules>(entity =>
            {
                entity.Property(e => e.IpAddress).IsFixedLength(true);

                entity.Property(e => e.MacAddress).IsUnicode(false);

                entity.Property(e => e.Name).IsUnicode(false);
            });

            modelBuilder.Entity<SystemConfig>(entity =>
            {
                entity.Property(e => e.HostName).IsUnicode(false);

                entity.Property(e => e.Ip).IsFixedLength(true);

                entity.Property(e => e.Password).IsUnicode(false);

                entity.Property(e => e.Ssid).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}