// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataCommunicator.Models
{
    public partial class Modules
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(17)]
        public string MacAddress { get; set; }
        [Required]
        [StringLength(10)]
        public string IpAddress { get; set; }
        public ModulesType? Type { get; set; }
        public bool? Status { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
    }
}