// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataCommunicator.Models
{
    public partial class SystemConfig
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string HostName { get; set; }
        [Column("IP")]
        [StringLength(10)]
        public string Ip { get; set; }
        [Column("SSID")]
        [Display(Name = "Nome da rede", Description = "Nome da rede")]
        [StringLength(50)]
        public string Ssid { get; set; }
        [Display(Name = "Nome da rede", Description = "Senha da rede")]
        [StringLength(50)]
        public string Password { get; set; }
    }
}